export { restApiFetcher } from './fetcher'
export { musicApiFetcher } from './fetcher/music-api.fetcher'
export { default as RestApiProvider } from './rest-api.provider'
export { getQueryClient } from './service'
export * from './service/music.service'